nginx:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - .:/app
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

php:
    build: ./
    volumes:
       - .:/app
